-- 001_phase_1_foundation.cjs up
-- SQL migration for MySQL.

create table `persons` (`id` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `employee_code` varchar(64), `first_name` varchar(120) not null, `last_name` varchar(120), `display_name` varchar(180) not null, `father_name` varchar(120), `email` varchar(191), `phone` varchar(40), `status` varchar(40) not null default 'active', `created_at` timestamp not null default CURRENT_TIMESTAMP, `updated_at` timestamp not null default CURRENT_TIMESTAMP, `deleted_at` timestamp null);
alter table `persons` add unique `persons_uuid_unique`(`uuid`);
alter table `persons` add unique `persons_employee_code_unique`(`employee_code`);
alter table `persons` add unique `persons_email_unique`(`email`);
alter table `persons` add index `persons_status_index`(`status`);
create table `users` (`id` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `person_id` bigint unsigned not null, `email` varchar(191) not null, `username` varchar(80) not null, `password_hash` varchar(255) not null, `status` varchar(40) not null default 'pending_activation', `must_change_password` boolean not null default '1', `failed_login_attempts` int unsigned not null default '0', `locked_until` timestamp null, `last_login_at` timestamp null, `created_at` timestamp not null default CURRENT_TIMESTAMP, `updated_at` timestamp not null default CURRENT_TIMESTAMP, `deleted_at` timestamp null);
alter table `users` add unique `users_uuid_unique`(`uuid`);
alter table `users` add unique `users_email_unique`(`email`);
alter table `users` add unique `users_username_unique`(`username`);
alter table `users` add constraint `users_person_id_foreign` foreign key (`person_id`) references `persons` (`id`) on delete RESTRICT;
alter table `users` add index `users_person_id_index`(`person_id`);
alter table `users` add index `users_status_index`(`status`);
create table `user_activation_tokens` (`id` bigint unsigned not null auto_increment primary key, `user_id` bigint unsigned not null, `token_hash` varchar(255) not null, `expires_at` timestamp not null, `consumed_at` timestamp null, `created_at` timestamp not null default CURRENT_TIMESTAMP);
alter table `user_activation_tokens` add unique `user_activation_tokens_token_hash_unique`(`token_hash`);
alter table `user_activation_tokens` add constraint `user_activation_tokens_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete CASCADE;
alter table `user_activation_tokens` add index `user_activation_tokens_user_id_expires_at_index`(`user_id`, `expires_at`);
create table `password_reset_tokens` (`id` bigint unsigned not null auto_increment primary key, `user_id` bigint unsigned not null, `token_hash` varchar(255) not null, `expires_at` timestamp not null, `consumed_at` timestamp null, `created_at` timestamp not null default CURRENT_TIMESTAMP);
alter table `password_reset_tokens` add unique `password_reset_tokens_token_hash_unique`(`token_hash`);
alter table `password_reset_tokens` add constraint `password_reset_tokens_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete CASCADE;
alter table `password_reset_tokens` add index `password_reset_tokens_user_id_expires_at_index`(`user_id`, `expires_at`);
create table `sessions` (`session_id` varchar(128) not null, `expires` int unsigned not null, `data` MEDIUMTEXT null, primary key (`session_id`));
alter table `sessions` add index `sessions_expires_index`(`expires`);
create table `roles` (`id` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `name` varchar(80) not null, `display_name` varchar(120) not null, `description` text, `is_system` boolean not null default '0', `created_at` timestamp not null default CURRENT_TIMESTAMP, `updated_at` timestamp not null default CURRENT_TIMESTAMP);
alter table `roles` add unique `roles_uuid_unique`(`uuid`);
alter table `roles` add unique `roles_name_unique`(`name`);
create table `user_roles` (`user_id` bigint unsigned not null, `role_id` bigint unsigned not null, `assigned_by_user_id` bigint unsigned, `created_at` timestamp not null default CURRENT_TIMESTAMP, primary key (`user_id`, `role_id`));
alter table `user_roles` add constraint `user_roles_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete CASCADE;
alter table `user_roles` add constraint `user_roles_role_id_foreign` foreign key (`role_id`) references `roles` (`id`) on delete CASCADE;
alter table `user_roles` add constraint `user_roles_assigned_by_user_id_foreign` foreign key (`assigned_by_user_id`) references `users` (`id`) on delete SET NULL;
create table `organizations` (`id` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `code` varchar(64) not null, `name` varchar(180) not null, `name_local` varchar(180), `description` text, `status` varchar(40) not null default 'active', `created_at` timestamp not null default CURRENT_TIMESTAMP, `updated_at` timestamp not null default CURRENT_TIMESTAMP, `deleted_at` timestamp null);
alter table `organizations` add unique `organizations_uuid_unique`(`uuid`);
alter table `organizations` add unique `organizations_code_unique`(`code`);
alter table `organizations` add index `organizations_status_index`(`status`);
create table `unit_types` (`id` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `code` varchar(80) not null, `name` varchar(120) not null, `hierarchy_level` int unsigned not null default '0', `allows_children` boolean not null default '1', `description` text, `created_at` timestamp not null default CURRENT_TIMESTAMP, `updated_at` timestamp not null default CURRENT_TIMESTAMP);
alter table `unit_types` add unique `unit_types_uuid_unique`(`uuid`);
alter table `unit_types` add unique `unit_types_code_unique`(`code`);
create table `units` (`id` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `organization_id` bigint unsigned not null, `unit_type_id` bigint unsigned not null, `parent_unit_id` bigint unsigned, `code` varchar(80) not null, `name` varchar(180) not null, `name_local` varchar(180), `description` text, `status` varchar(40) not null default 'active', `created_at` timestamp not null default CURRENT_TIMESTAMP, `updated_at` timestamp not null default CURRENT_TIMESTAMP, `deleted_at` timestamp null);
alter table `units` add unique `units_uuid_unique`(`uuid`);
alter table `units` add unique `units_organization_id_code_unique`(`organization_id`, `code`);
alter table `units` add constraint `units_organization_id_foreign` foreign key (`organization_id`) references `organizations` (`id`) on delete RESTRICT;
alter table `units` add constraint `units_unit_type_id_foreign` foreign key (`unit_type_id`) references `unit_types` (`id`) on delete RESTRICT;
alter table `units` add constraint `units_parent_unit_id_foreign` foreign key (`parent_unit_id`) references `units` (`id`) on delete SET NULL;
alter table `units` add index `units_parent_unit_id_index`(`parent_unit_id`);
alter table `units` add index `units_status_index`(`status`);
create table `positions` (`id` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `organization_id` bigint unsigned, `code` varchar(80) not null, `title` varchar(140) not null, `title_local` varchar(140), `authority_level` int unsigned not null default '0', `is_signing_authority` boolean not null default '0', `description` text, `status` varchar(40) not null default 'active', `created_at` timestamp not null default CURRENT_TIMESTAMP, `updated_at` timestamp not null default CURRENT_TIMESTAMP, `deleted_at` timestamp null);
alter table `positions` add unique `positions_uuid_unique`(`uuid`);
alter table `positions` add unique `positions_code_unique`(`code`);
alter table `positions` add constraint `positions_organization_id_foreign` foreign key (`organization_id`) references `organizations` (`id`) on delete SET NULL;
alter table `positions` add index `positions_status_index`(`status`);
create table `assignments` (`id` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `person_id` bigint unsigned not null, `unit_id` bigint unsigned not null, `position_id` bigint unsigned not null, `status` varchar(40) not null default 'active', `is_primary` boolean not null default '0', `starts_at` timestamp null, `ends_at` timestamp null, `created_by_user_id` bigint unsigned, `created_at` timestamp not null default CURRENT_TIMESTAMP, `updated_at` timestamp not null default CURRENT_TIMESTAMP, `deleted_at` timestamp null);
alter table `assignments` add unique `assignments_uuid_unique`(`uuid`);
alter table `assignments` add constraint `assignments_person_id_foreign` foreign key (`person_id`) references `persons` (`id`) on delete RESTRICT;
alter table `assignments` add constraint `assignments_unit_id_foreign` foreign key (`unit_id`) references `units` (`id`) on delete RESTRICT;
alter table `assignments` add constraint `assignments_position_id_foreign` foreign key (`position_id`) references `positions` (`id`) on delete RESTRICT;
alter table `assignments` add constraint `assignments_created_by_user_id_foreign` foreign key (`created_by_user_id`) references `users` (`id`) on delete SET NULL;
alter table `assignments` add index `assignments_person_id_status_index`(`person_id`, `status`);
alter table `assignments` add index `assignments_unit_id_position_id_index`(`unit_id`, `position_id`);
create table `assignment_status_history` (`id` bigint unsigned not null auto_increment primary key, `assignment_id` bigint unsigned not null, `from_status` varchar(40), `to_status` varchar(40) not null, `reason` text, `changed_by_user_id` bigint unsigned, `created_at` timestamp not null default CURRENT_TIMESTAMP);
alter table `assignment_status_history` add constraint `assignment_status_history_assignment_id_foreign` foreign key (`assignment_id`) references `assignments` (`id`) on delete CASCADE;
alter table `assignment_status_history` add constraint `assignment_status_history_changed_by_user_id_foreign` foreign key (`changed_by_user_id`) references `users` (`id`) on delete SET NULL;
alter table `assignment_status_history` add index `assignment_status_history_assignment_id_created_at_index`(`assignment_id`, `created_at`);
create table `document_types` (`id` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `code` varchar(80) not null, `name` varchar(140) not null, `description` text, `requires_serial` boolean not null default '1', `status` varchar(40) not null default 'active', `created_at` timestamp not null default CURRENT_TIMESTAMP, `updated_at` timestamp not null default CURRENT_TIMESTAMP);
alter table `document_types` add unique `document_types_uuid_unique`(`uuid`);
alter table `document_types` add unique `document_types_code_unique`(`code`);
alter table `document_types` add index `document_types_status_index`(`status`);
create table `confidentiality_levels` (`id` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `code` varchar(80) not null, `name` varchar(140) not null, `rank` int unsigned not null default '0', `is_default` boolean not null default '0', `requires_access_log` boolean not null default '0', `description` text, `status` varchar(40) not null default 'active', `created_at` timestamp not null default CURRENT_TIMESTAMP, `updated_at` timestamp not null default CURRENT_TIMESTAMP);
alter table `confidentiality_levels` add unique `confidentiality_levels_uuid_unique`(`uuid`);
alter table `confidentiality_levels` add unique `confidentiality_levels_code_unique`(`code`);
alter table `confidentiality_levels` add index `confidentiality_levels_rank_index`(`rank`);
alter table `confidentiality_levels` add index `confidentiality_levels_status_index`(`status`);
create table `priority_levels` (`id` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `code` varchar(80) not null, `name` varchar(140) not null, `rank` int unsigned not null default '0', `default_due_days` int unsigned, `color` varchar(32), `description` text, `status` varchar(40) not null default 'active', `created_at` timestamp not null default CURRENT_TIMESTAMP, `updated_at` timestamp not null default CURRENT_TIMESTAMP);
alter table `priority_levels` add unique `priority_levels_uuid_unique`(`uuid`);
alter table `priority_levels` add unique `priority_levels_code_unique`(`code`);
alter table `priority_levels` add index `priority_levels_rank_index`(`rank`);
alter table `priority_levels` add index `priority_levels_status_index`(`status`);
create table `audit_logs` (`id` bigint unsigned not null auto_increment primary key, `actor_user_id` bigint unsigned, `actor_assignment_id` bigint unsigned, `action` varchar(120) not null, `entity_type` varchar(120) not null, `entity_id` varchar(120), `ip_address` varchar(80), `user_agent` text, `metadata` json, `created_at` timestamp not null default CURRENT_TIMESTAMP);
alter table `audit_logs` add constraint `audit_logs_actor_user_id_foreign` foreign key (`actor_user_id`) references `users` (`id`) on delete SET NULL;
alter table `audit_logs` add constraint `audit_logs_actor_assignment_id_foreign` foreign key (`actor_assignment_id`) references `assignments` (`id`) on delete SET NULL;
alter table `audit_logs` add index `audit_logs_action_created_at_index`(`action`, `created_at`);
alter table `audit_logs` add index `audit_logs_entity_type_entity_id_index`(`entity_type`, `entity_id`);
create table `access_logs` (`id` bigint unsigned not null auto_increment primary key, `user_id` bigint unsigned, `assignment_id` bigint unsigned, `action` varchar(80) not null, `resource_type` varchar(120) not null, `resource_id` varchar(120), `ip_address` varchar(80), `user_agent` text, `metadata` json, `created_at` timestamp not null default CURRENT_TIMESTAMP);
alter table `access_logs` add constraint `access_logs_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete SET NULL;
alter table `access_logs` add constraint `access_logs_assignment_id_foreign` foreign key (`assignment_id`) references `assignments` (`id`) on delete SET NULL;
alter table `access_logs` add index `access_logs_resource_type_resource_id_index`(`resource_type`, `resource_id`);
alter table `access_logs` add index `access_logs_action_created_at_index`(`action`, `created_at`);
create table `admin_override_logs` (`id` bigint unsigned not null auto_increment primary key, `admin_user_id` bigint unsigned, `admin_assignment_id` bigint unsigned, `override_type` varchar(120) not null, `target_type` varchar(120) not null, `target_id` varchar(120), `reason` text not null, `metadata` json, `created_at` timestamp not null default CURRENT_TIMESTAMP);
alter table `admin_override_logs` add constraint `admin_override_logs_admin_user_id_foreign` foreign key (`admin_user_id`) references `users` (`id`) on delete SET NULL;
alter table `admin_override_logs` add constraint `admin_override_logs_admin_assignment_id_foreign` foreign key (`admin_assignment_id`) references `assignments` (`id`) on delete SET NULL;
alter table `admin_override_logs` add index `admin_override_logs_target_type_target_id_index`(`target_type`, `target_id`);
alter table `admin_override_logs` add index `admin_override_logs_override_type_created_at_index`(`override_type`, `created_at`);
