-- 002_phase_2_documents_workflow.cjs up
-- SQL migration for MySQL.

create table `file_assets` (`id` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `uploaded_by_user_id` bigint unsigned, `uploaded_by_assignment_id` bigint unsigned, `purpose` varchar(80) not null, `storage_disk` varchar(80) not null default 'local', `storage_path` varchar(500) not null, `original_filename` varchar(255) not null, `stored_filename` varchar(255), `mime_type` varchar(160) not null, `byte_size` bigint unsigned not null, `checksum_sha256` varchar(64), `encryption_status` varchar(40) not null default 'not_encrypted', `status` varchar(40) not null default 'active', `metadata` json, `created_at` timestamp not null default CURRENT_TIMESTAMP, `updated_at` timestamp not null default CURRENT_TIMESTAMP, `deleted_at` timestamp null);
alter table `file_assets` add unique `file_assets_uuid_unique`(`uuid`);
alter table `file_assets` add constraint `file_assets_uploaded_by_user_id_foreign` foreign key (`uploaded_by_user_id`) references `users` (`id`) on delete SET NULL;
alter table `file_assets` add constraint `file_assets_uploaded_by_assignment_id_foreign` foreign key (`uploaded_by_assignment_id`) references `assignments` (`id`) on delete SET NULL;
alter table `file_assets` add index `file_assets_purpose_status_index`(`purpose`, `status`);
alter table `file_assets` add index `file_assets_checksum_sha256_index`(`checksum_sha256`);
create table `documents` (`id` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `internal_reference` varchar(80) not null, `document_type_id` bigint unsigned not null, `subject` varchar(255) not null, `summary` text, `body` MEDIUMTEXT, `origin_unit_id` bigint unsigned not null, `owner_unit_id` bigint unsigned not null, `current_holder_unit_id` bigint unsigned not null, `creator_assignment_id` bigint unsigned not null, `confidentiality_level_id` bigint unsigned not null, `priority_level_id` bigint unsigned not null, `status` varchar(60) not null default 'draft', `current_version_number` int unsigned not null default '1', `official_serial` varchar(120), `finalized_at` timestamp null, `finalized_by_assignment_id` bigint unsigned, `official_serial_generated_at` timestamp null, `official_serial_generated_by_assignment_id` bigint unsigned, `closed_at` timestamp null, `archived_at` timestamp null, `archived_by_assignment_id` bigint unsigned, `archive_reason` text, `created_at` timestamp not null default CURRENT_TIMESTAMP, `updated_at` timestamp not null default CURRENT_TIMESTAMP, `deleted_at` timestamp null);
alter table `documents` add unique `documents_uuid_unique`(`uuid`);
alter table `documents` add unique `documents_internal_reference_unique`(`internal_reference`);
alter table `documents` add unique `documents_official_serial_unique`(`official_serial`);
alter table `documents` add constraint `documents_document_type_id_foreign` foreign key (`document_type_id`) references `document_types` (`id`) on delete RESTRICT;
alter table `documents` add constraint `documents_origin_unit_id_foreign` foreign key (`origin_unit_id`) references `units` (`id`) on delete RESTRICT;
alter table `documents` add constraint `documents_owner_unit_id_foreign` foreign key (`owner_unit_id`) references `units` (`id`) on delete RESTRICT;
alter table `documents` add constraint `documents_current_holder_unit_id_foreign` foreign key (`current_holder_unit_id`) references `units` (`id`) on delete RESTRICT;
alter table `documents` add constraint `documents_creator_assignment_id_foreign` foreign key (`creator_assignment_id`) references `assignments` (`id`) on delete RESTRICT;
alter table `documents` add constraint `documents_confidentiality_level_id_foreign` foreign key (`confidentiality_level_id`) references `confidentiality_levels` (`id`) on delete RESTRICT;
alter table `documents` add constraint `documents_priority_level_id_foreign` foreign key (`priority_level_id`) references `priority_levels` (`id`) on delete RESTRICT;
alter table `documents` add constraint `documents_finalized_by_assignment_id_foreign` foreign key (`finalized_by_assignment_id`) references `assignments` (`id`) on delete SET NULL;
alter table `documents` add constraint `documents_official_serial_generated_by_assignment_id_foreign` foreign key (`official_serial_generated_by_assignment_id`) references `assignments` (`id`) on delete SET NULL;
alter table `documents` add constraint `documents_archived_by_assignment_id_foreign` foreign key (`archived_by_assignment_id`) references `assignments` (`id`) on delete SET NULL;
alter table `documents` add index `documents_status_created_at_index`(`status`, `created_at`);
alter table `documents` add index `documents_document_type_id_status_index`(`document_type_id`, `status`);
alter table `documents` add index `documents_origin_unit_id_status_index`(`origin_unit_id`, `status`);
alter table `documents` add index `documents_current_holder_unit_id_status_index`(`current_holder_unit_id`, `status`);
alter table `documents` add index `documents_creator_assignment_id_index`(`creator_assignment_id`);
create table `document_versions` (`id` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `document_id` bigint unsigned not null, `version_number` int unsigned not null, `changed_by_assignment_id` bigint unsigned not null, `subject` varchar(255) not null, `summary` text, `body` MEDIUMTEXT, `material_change` boolean not null default '1', `change_reason` text, `snapshot` json, `created_at` timestamp not null default CURRENT_TIMESTAMP);
alter table `document_versions` add unique `document_versions_uuid_unique`(`uuid`);
alter table `document_versions` add unique `document_versions_document_id_version_number_unique`(`document_id`, `version_number`);
alter table `document_versions` add constraint `document_versions_document_id_foreign` foreign key (`document_id`) references `documents` (`id`) on delete CASCADE;
alter table `document_versions` add constraint `document_versions_changed_by_assignment_id_foreign` foreign key (`changed_by_assignment_id`) references `assignments` (`id`) on delete RESTRICT;
alter table `document_versions` add index `document_versions_changed_by_assignment_id_created_at_index`(`changed_by_assignment_id`, `created_at`);
create table `document_relations` (`id` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `source_document_id` bigint unsigned not null, `related_document_id` bigint unsigned not null, `relation_type` varchar(60) not null, `created_by_assignment_id` bigint unsigned, `note` text, `created_at` timestamp not null default CURRENT_TIMESTAMP);
alter table `document_relations` add unique `document_relations_uuid_unique`(`uuid`);
alter table `document_relations` add unique `doc_rel_src_related_type_uq`(`source_document_id`, `related_document_id`, `relation_type`);
alter table `document_relations` add constraint `document_relations_source_document_id_foreign` foreign key (`source_document_id`) references `documents` (`id`) on delete CASCADE;
alter table `document_relations` add constraint `document_relations_related_document_id_foreign` foreign key (`related_document_id`) references `documents` (`id`) on delete CASCADE;
alter table `document_relations` add constraint `document_relations_created_by_assignment_id_foreign` foreign key (`created_by_assignment_id`) references `assignments` (`id`) on delete SET NULL;
alter table `document_relations` add index `document_relations_related_document_id_relation_type_index`(`related_document_id`, `relation_type`);
create table `document_attachments` (`id` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `document_id` bigint unsigned not null, `file_asset_id` bigint unsigned not null, `uploaded_by_assignment_id` bigint unsigned, `attachment_type` varchar(80) not null default 'supporting_file', `title` varchar(180), `description` text, `status` varchar(40) not null default 'active', `created_at` timestamp not null default CURRENT_TIMESTAMP, `updated_at` timestamp not null default CURRENT_TIMESTAMP, `deleted_at` timestamp null);
alter table `document_attachments` add unique `document_attachments_uuid_unique`(`uuid`);
alter table `document_attachments` add constraint `document_attachments_document_id_foreign` foreign key (`document_id`) references `documents` (`id`) on delete CASCADE;
alter table `document_attachments` add constraint `document_attachments_file_asset_id_foreign` foreign key (`file_asset_id`) references `file_assets` (`id`) on delete RESTRICT;
alter table `document_attachments` add constraint `document_attachments_uploaded_by_assignment_id_foreign` foreign key (`uploaded_by_assignment_id`) references `assignments` (`id`) on delete SET NULL;
alter table `document_attachments` add index `document_attachments_document_id_status_index`(`document_id`, `status`);
alter table `document_attachments` add index `document_attachments_file_asset_id_index`(`file_asset_id`);
create table `routing_rules` (`id` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `document_type_id` bigint unsigned, `from_unit_type_id` bigint unsigned, `from_position_id` bigint unsigned, `to_unit_type_id` bigint unsigned, `to_position_id` bigint unsigned, `action` varchar(80) not null, `allowed` varchar(40) not null default 'allowed', `prior_review_required` boolean not null default '0', `prior_signature_required` boolean not null default '0', `is_external_target` boolean not null default '0', `is_multi_recipient` boolean not null default '0', `priority` int unsigned not null default '100', `status` varchar(40) not null default 'draft', `effective_from` timestamp null, `effective_until` timestamp null, `activated_by_user_id` bigint unsigned, `activated_at` timestamp null, `notes` text, `created_at` timestamp not null default CURRENT_TIMESTAMP, `updated_at` timestamp not null default CURRENT_TIMESTAMP);
alter table `routing_rules` add unique `routing_rules_uuid_unique`(`uuid`);
alter table `routing_rules` add constraint `routing_rules_document_type_id_foreign` foreign key (`document_type_id`) references `document_types` (`id`) on delete SET NULL;
alter table `routing_rules` add constraint `routing_rules_from_unit_type_id_foreign` foreign key (`from_unit_type_id`) references `unit_types` (`id`) on delete SET NULL;
alter table `routing_rules` add constraint `routing_rules_from_position_id_foreign` foreign key (`from_position_id`) references `positions` (`id`) on delete SET NULL;
alter table `routing_rules` add constraint `routing_rules_to_unit_type_id_foreign` foreign key (`to_unit_type_id`) references `unit_types` (`id`) on delete SET NULL;
alter table `routing_rules` add constraint `routing_rules_to_position_id_foreign` foreign key (`to_position_id`) references `positions` (`id`) on delete SET NULL;
alter table `routing_rules` add constraint `routing_rules_activated_by_user_id_foreign` foreign key (`activated_by_user_id`) references `users` (`id`) on delete SET NULL;
alter table `routing_rules` add index `routing_rules_action_status_index`(`action`, `status`);
alter table `routing_rules` add index `routing_rules_document_type_id_action_index`(`document_type_id`, `action`);
create table `workflow_rule_conditions` (`id` bigint unsigned not null auto_increment primary key, `routing_rule_id` bigint unsigned not null, `condition_key` varchar(120) not null, `operator` varchar(40) not null default 'equals', `condition_value` varchar(255) not null, `is_required` boolean not null default '1', `created_at` timestamp not null default CURRENT_TIMESTAMP);
alter table `workflow_rule_conditions` add constraint `workflow_rule_conditions_routing_rule_id_foreign` foreign key (`routing_rule_id`) references `routing_rules` (`id`) on delete CASCADE;
alter table `workflow_rule_conditions` add index `workflow_rule_conditions_routing_rule_id_condition_key_index`(`routing_rule_id`, `condition_key`);
create table `document_workflow_events` (`id` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `document_id` bigint unsigned not null, `actor_assignment_id` bigint unsigned not null, `routing_rule_id` bigint unsigned, `action` varchar(80) not null, `from_status` varchar(60), `to_status` varchar(60), `from_unit_id` bigint unsigned, `to_unit_id` bigint unsigned, `note` text, `return_reason` text, `payload` json, `created_at` timestamp not null default CURRENT_TIMESTAMP);
alter table `document_workflow_events` add unique `document_workflow_events_uuid_unique`(`uuid`);
alter table `document_workflow_events` add constraint `document_workflow_events_document_id_foreign` foreign key (`document_id`) references `documents` (`id`) on delete CASCADE;
alter table `document_workflow_events` add constraint `document_workflow_events_actor_assignment_id_foreign` foreign key (`actor_assignment_id`) references `assignments` (`id`) on delete RESTRICT;
alter table `document_workflow_events` add constraint `document_workflow_events_routing_rule_id_foreign` foreign key (`routing_rule_id`) references `routing_rules` (`id`) on delete SET NULL;
alter table `document_workflow_events` add constraint `document_workflow_events_from_unit_id_foreign` foreign key (`from_unit_id`) references `units` (`id`) on delete SET NULL;
alter table `document_workflow_events` add constraint `document_workflow_events_to_unit_id_foreign` foreign key (`to_unit_id`) references `units` (`id`) on delete SET NULL;
alter table `document_workflow_events` add index `document_workflow_events_document_id_created_at_index`(`document_id`, `created_at`);
alter table `document_workflow_events` add index `document_workflow_events_actor_assignment_id_created_at_index`(`actor_assignment_id`, `created_at`);
alter table `document_workflow_events` add index `document_workflow_events_action_created_at_index`(`action`, `created_at`);
create table `document_tasks` (`id` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `document_id` bigint unsigned not null, `workflow_event_id` bigint unsigned, `created_by_assignment_id` bigint unsigned not null, `assigned_unit_id` bigint unsigned, `assigned_position_id` bigint unsigned, `assigned_assignment_id` bigint unsigned, `task_type` varchar(80) not null, `status` varchar(60) not null default 'open', `title` varchar(180) not null, `description` text, `due_at` timestamp null, `completed_at` timestamp null, `completed_by_assignment_id` bigint unsigned, `completion_note` text, `created_at` timestamp not null default CURRENT_TIMESTAMP, `updated_at` timestamp not null default CURRENT_TIMESTAMP, `deleted_at` timestamp null);
alter table `document_tasks` add unique `document_tasks_uuid_unique`(`uuid`);
alter table `document_tasks` add constraint `document_tasks_document_id_foreign` foreign key (`document_id`) references `documents` (`id`) on delete CASCADE;
alter table `document_tasks` add constraint `document_tasks_workflow_event_id_foreign` foreign key (`workflow_event_id`) references `document_workflow_events` (`id`) on delete SET NULL;
alter table `document_tasks` add constraint `document_tasks_created_by_assignment_id_foreign` foreign key (`created_by_assignment_id`) references `assignments` (`id`) on delete RESTRICT;
alter table `document_tasks` add constraint `document_tasks_assigned_unit_id_foreign` foreign key (`assigned_unit_id`) references `units` (`id`) on delete SET NULL;
alter table `document_tasks` add constraint `document_tasks_assigned_position_id_foreign` foreign key (`assigned_position_id`) references `positions` (`id`) on delete SET NULL;
alter table `document_tasks` add constraint `document_tasks_assigned_assignment_id_foreign` foreign key (`assigned_assignment_id`) references `assignments` (`id`) on delete SET NULL;
alter table `document_tasks` add constraint `document_tasks_completed_by_assignment_id_foreign` foreign key (`completed_by_assignment_id`) references `assignments` (`id`) on delete SET NULL;
alter table `document_tasks` add index `document_tasks_document_id_status_index`(`document_id`, `status`);
alter table `document_tasks` add index `document_tasks_assigned_assignment_id_status_index`(`assigned_assignment_id`, `status`);
alter table `document_tasks` add index `document_tasks_assigned_unit_id_status_index`(`assigned_unit_id`, `status`);
alter table `document_tasks` add index `document_tasks_due_at_index`(`due_at`);
